### ISSUE TITLE
0.5 Issues & PRs to be merged

### ISSUE THREAD

**Issue by MollyMaclachlan** [MurdoMaclachlan/clone-finder#3]
## Functionality

- [x] #1, #7: Add type hinting.

## Cleanup/Optimisation

- [x] #4, #6: Condense some strings with fstrings.

## Dependencies

- [x] Require Python 3.5+ as of #1.

## Bug Fixes

- [x] #5, fix #2: Crash if post is missing flair.
